name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "22.x"
          
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cache-node-modules-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Install
        run: pnpm install

      - name: Run CI
        run: pnpm run ci
